# Generated by Django 5.2.4 on 2025-09-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
